---  # local.yml

- hosts: localhost

  tasks:

    - name: Configure EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install packages
      ansible.builtin.dnf:
        name: 
          - vim-enhanced
          - cowsay
        state: present

...
